services:

  configserver:
    image: sfahafi/configserver:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - sfahafi-network

  hotels:
    image: sfahafi/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - sfahafi-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http//configserver:8085/

  rooms:
    image: sfahafi/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - sfahafi-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http//configserver:8085/
    
  reservations:
    image: sfahafi/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - sfahafi-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http//configserver:8085/
    
networks:
  sfahafi-network: